namespace LibraryAutomation
{
    partial class Home
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Home));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.btnAllBooks = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.lblDGV = new Bunifu.UI.WinForms.BunifuLabel();
            this.lblMain = new Bunifu.UI.WinForms.BunifuLabel();
            this.btnRentedBooks = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnAllAuthors = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnManageAuthors = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnManageBooks = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnRent = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dgv = new Bunifu.UI.WinForms.BunifuDataGridView();
            ((System.ComponentModel.ISupportInitialize)(this.dgv)).BeginInit();
            this.SuspendLayout();
            // 
            // btnAllBooks
            // 
            this.btnAllBooks.AllowAnimations = true;
            this.btnAllBooks.AllowMouseEffects = true;
            this.btnAllBooks.AllowToggling = false;
            this.btnAllBooks.AnimationSpeed = 200;
            this.btnAllBooks.AutoGenerateColors = false;
            this.btnAllBooks.AutoRoundBorders = false;
            this.btnAllBooks.AutoSizeLeftIcon = true;
            this.btnAllBooks.AutoSizeRightIcon = true;
            this.btnAllBooks.BackColor = System.Drawing.Color.Transparent;
            this.btnAllBooks.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnAllBooks.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAllBooks.BackgroundImage")));
            this.btnAllBooks.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllBooks.ButtonText = "Show All Books";
            this.btnAllBooks.ButtonTextMarginLeft = 0;
            this.btnAllBooks.ColorContrastOnClick = 45;
            this.btnAllBooks.ColorContrastOnHover = 45;
            this.btnAllBooks.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnAllBooks.CustomizableEdges = borderEdges1;
            this.btnAllBooks.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAllBooks.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAllBooks.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAllBooks.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAllBooks.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAllBooks.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnAllBooks.ForeColor = System.Drawing.Color.White;
            this.btnAllBooks.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAllBooks.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAllBooks.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAllBooks.IconMarginLeft = 11;
            this.btnAllBooks.IconPadding = 10;
            this.btnAllBooks.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAllBooks.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAllBooks.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAllBooks.IconSize = 25;
            this.btnAllBooks.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnAllBooks.IdleBorderRadius = 1;
            this.btnAllBooks.IdleBorderThickness = 1;
            this.btnAllBooks.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnAllBooks.IdleIconLeftImage = null;
            this.btnAllBooks.IdleIconRightImage = null;
            this.btnAllBooks.IndicateFocus = false;
            this.btnAllBooks.Location = new System.Drawing.Point(752, 136);
            this.btnAllBooks.Name = "btnAllBooks";
            this.btnAllBooks.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAllBooks.OnDisabledState.BorderRadius = 1;
            this.btnAllBooks.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllBooks.OnDisabledState.BorderThickness = 1;
            this.btnAllBooks.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAllBooks.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAllBooks.OnDisabledState.IconLeftImage = null;
            this.btnAllBooks.OnDisabledState.IconRightImage = null;
            this.btnAllBooks.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAllBooks.onHoverState.BorderRadius = 1;
            this.btnAllBooks.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllBooks.onHoverState.BorderThickness = 1;
            this.btnAllBooks.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAllBooks.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAllBooks.onHoverState.IconLeftImage = null;
            this.btnAllBooks.onHoverState.IconRightImage = null;
            this.btnAllBooks.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnAllBooks.OnIdleState.BorderRadius = 1;
            this.btnAllBooks.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllBooks.OnIdleState.BorderThickness = 1;
            this.btnAllBooks.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnAllBooks.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAllBooks.OnIdleState.IconLeftImage = null;
            this.btnAllBooks.OnIdleState.IconRightImage = null;
            this.btnAllBooks.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAllBooks.OnPressedState.BorderRadius = 1;
            this.btnAllBooks.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllBooks.OnPressedState.BorderThickness = 1;
            this.btnAllBooks.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAllBooks.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAllBooks.OnPressedState.IconLeftImage = null;
            this.btnAllBooks.OnPressedState.IconRightImage = null;
            this.btnAllBooks.Size = new System.Drawing.Size(154, 35);
            this.btnAllBooks.TabIndex = 0;
            this.btnAllBooks.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAllBooks.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAllBooks.TextMarginLeft = 0;
            this.btnAllBooks.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAllBooks.UseDefaultRadiusAndThickness = true;
            this.btnAllBooks.Click += new System.EventHandler(this.btnAllBooks_Click);
            // 
            // lblDGV
            // 
            this.lblDGV.AllowParentOverrides = false;
            this.lblDGV.AutoEllipsis = false;
            this.lblDGV.Cursor = System.Windows.Forms.Cursors.Default;
            this.lblDGV.CursorType = System.Windows.Forms.Cursors.Default;
            this.lblDGV.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblDGV.Location = new System.Drawing.Point(33, 68);
            this.lblDGV.Name = "lblDGV";
            this.lblDGV.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblDGV.Size = new System.Drawing.Size(60, 21);
            this.lblDGV.TabIndex = 2;
            this.lblDGV.Text = "Authors";
            this.lblDGV.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblDGV.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // lblMain
            // 
            this.lblMain.AllowParentOverrides = false;
            this.lblMain.AutoEllipsis = false;
            this.lblMain.CursorType = null;
            this.lblMain.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.lblMain.Location = new System.Drawing.Point(33, 29);
            this.lblMain.Name = "lblMain";
            this.lblMain.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.lblMain.Size = new System.Drawing.Size(239, 21);
            this.lblMain.TabIndex = 3;
            this.lblMain.Text = "Library Automation Main Panel";
            this.lblMain.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.lblMain.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // btnRentedBooks
            // 
            this.btnRentedBooks.AllowAnimations = true;
            this.btnRentedBooks.AllowMouseEffects = true;
            this.btnRentedBooks.AllowToggling = false;
            this.btnRentedBooks.AnimationSpeed = 200;
            this.btnRentedBooks.AutoGenerateColors = false;
            this.btnRentedBooks.AutoRoundBorders = false;
            this.btnRentedBooks.AutoSizeLeftIcon = true;
            this.btnRentedBooks.AutoSizeRightIcon = true;
            this.btnRentedBooks.BackColor = System.Drawing.Color.Transparent;
            this.btnRentedBooks.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnRentedBooks.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRentedBooks.BackgroundImage")));
            this.btnRentedBooks.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRentedBooks.ButtonText = "Show Rented Books";
            this.btnRentedBooks.ButtonTextMarginLeft = 0;
            this.btnRentedBooks.ColorContrastOnClick = 45;
            this.btnRentedBooks.ColorContrastOnHover = 45;
            this.btnRentedBooks.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnRentedBooks.CustomizableEdges = borderEdges2;
            this.btnRentedBooks.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRentedBooks.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRentedBooks.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRentedBooks.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRentedBooks.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRentedBooks.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnRentedBooks.ForeColor = System.Drawing.Color.White;
            this.btnRentedBooks.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRentedBooks.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRentedBooks.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRentedBooks.IconMarginLeft = 11;
            this.btnRentedBooks.IconPadding = 10;
            this.btnRentedBooks.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRentedBooks.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRentedBooks.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRentedBooks.IconSize = 25;
            this.btnRentedBooks.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnRentedBooks.IdleBorderRadius = 1;
            this.btnRentedBooks.IdleBorderThickness = 1;
            this.btnRentedBooks.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnRentedBooks.IdleIconLeftImage = null;
            this.btnRentedBooks.IdleIconRightImage = null;
            this.btnRentedBooks.IndicateFocus = false;
            this.btnRentedBooks.Location = new System.Drawing.Point(752, 177);
            this.btnRentedBooks.Name = "btnRentedBooks";
            this.btnRentedBooks.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRentedBooks.OnDisabledState.BorderRadius = 1;
            this.btnRentedBooks.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRentedBooks.OnDisabledState.BorderThickness = 1;
            this.btnRentedBooks.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRentedBooks.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRentedBooks.OnDisabledState.IconLeftImage = null;
            this.btnRentedBooks.OnDisabledState.IconRightImage = null;
            this.btnRentedBooks.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRentedBooks.onHoverState.BorderRadius = 1;
            this.btnRentedBooks.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRentedBooks.onHoverState.BorderThickness = 1;
            this.btnRentedBooks.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRentedBooks.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnRentedBooks.onHoverState.IconLeftImage = null;
            this.btnRentedBooks.onHoverState.IconRightImage = null;
            this.btnRentedBooks.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnRentedBooks.OnIdleState.BorderRadius = 1;
            this.btnRentedBooks.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRentedBooks.OnIdleState.BorderThickness = 1;
            this.btnRentedBooks.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnRentedBooks.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnRentedBooks.OnIdleState.IconLeftImage = null;
            this.btnRentedBooks.OnIdleState.IconRightImage = null;
            this.btnRentedBooks.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRentedBooks.OnPressedState.BorderRadius = 1;
            this.btnRentedBooks.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRentedBooks.OnPressedState.BorderThickness = 1;
            this.btnRentedBooks.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRentedBooks.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRentedBooks.OnPressedState.IconLeftImage = null;
            this.btnRentedBooks.OnPressedState.IconRightImage = null;
            this.btnRentedBooks.Size = new System.Drawing.Size(154, 35);
            this.btnRentedBooks.TabIndex = 4;
            this.btnRentedBooks.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRentedBooks.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRentedBooks.TextMarginLeft = 0;
            this.btnRentedBooks.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRentedBooks.UseDefaultRadiusAndThickness = true;
            // 
            // btnAllAuthors
            // 
            this.btnAllAuthors.AllowAnimations = true;
            this.btnAllAuthors.AllowMouseEffects = true;
            this.btnAllAuthors.AllowToggling = false;
            this.btnAllAuthors.AnimationSpeed = 200;
            this.btnAllAuthors.AutoGenerateColors = false;
            this.btnAllAuthors.AutoRoundBorders = false;
            this.btnAllAuthors.AutoSizeLeftIcon = true;
            this.btnAllAuthors.AutoSizeRightIcon = true;
            this.btnAllAuthors.BackColor = System.Drawing.Color.Transparent;
            this.btnAllAuthors.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnAllAuthors.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnAllAuthors.BackgroundImage")));
            this.btnAllAuthors.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllAuthors.ButtonText = "Show All Authors";
            this.btnAllAuthors.ButtonTextMarginLeft = 0;
            this.btnAllAuthors.ColorContrastOnClick = 45;
            this.btnAllAuthors.ColorContrastOnHover = 45;
            this.btnAllAuthors.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnAllAuthors.CustomizableEdges = borderEdges3;
            this.btnAllAuthors.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnAllAuthors.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAllAuthors.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAllAuthors.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAllAuthors.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnAllAuthors.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnAllAuthors.ForeColor = System.Drawing.Color.White;
            this.btnAllAuthors.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnAllAuthors.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnAllAuthors.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnAllAuthors.IconMarginLeft = 11;
            this.btnAllAuthors.IconPadding = 10;
            this.btnAllAuthors.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnAllAuthors.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnAllAuthors.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnAllAuthors.IconSize = 25;
            this.btnAllAuthors.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnAllAuthors.IdleBorderRadius = 1;
            this.btnAllAuthors.IdleBorderThickness = 1;
            this.btnAllAuthors.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnAllAuthors.IdleIconLeftImage = null;
            this.btnAllAuthors.IdleIconRightImage = null;
            this.btnAllAuthors.IndicateFocus = false;
            this.btnAllAuthors.Location = new System.Drawing.Point(752, 95);
            this.btnAllAuthors.Name = "btnAllAuthors";
            this.btnAllAuthors.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnAllAuthors.OnDisabledState.BorderRadius = 1;
            this.btnAllAuthors.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllAuthors.OnDisabledState.BorderThickness = 1;
            this.btnAllAuthors.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnAllAuthors.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnAllAuthors.OnDisabledState.IconLeftImage = null;
            this.btnAllAuthors.OnDisabledState.IconRightImage = null;
            this.btnAllAuthors.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAllAuthors.onHoverState.BorderRadius = 1;
            this.btnAllAuthors.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllAuthors.onHoverState.BorderThickness = 1;
            this.btnAllAuthors.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnAllAuthors.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnAllAuthors.onHoverState.IconLeftImage = null;
            this.btnAllAuthors.onHoverState.IconRightImage = null;
            this.btnAllAuthors.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnAllAuthors.OnIdleState.BorderRadius = 1;
            this.btnAllAuthors.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllAuthors.OnIdleState.BorderThickness = 1;
            this.btnAllAuthors.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnAllAuthors.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnAllAuthors.OnIdleState.IconLeftImage = null;
            this.btnAllAuthors.OnIdleState.IconRightImage = null;
            this.btnAllAuthors.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAllAuthors.OnPressedState.BorderRadius = 1;
            this.btnAllAuthors.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnAllAuthors.OnPressedState.BorderThickness = 1;
            this.btnAllAuthors.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnAllAuthors.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnAllAuthors.OnPressedState.IconLeftImage = null;
            this.btnAllAuthors.OnPressedState.IconRightImage = null;
            this.btnAllAuthors.Size = new System.Drawing.Size(154, 35);
            this.btnAllAuthors.TabIndex = 5;
            this.btnAllAuthors.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnAllAuthors.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnAllAuthors.TextMarginLeft = 0;
            this.btnAllAuthors.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnAllAuthors.UseDefaultRadiusAndThickness = true;
            this.btnAllAuthors.Click += new System.EventHandler(this.btnAllAuthors_Click);
            // 
            // btnManageAuthors
            // 
            this.btnManageAuthors.AllowAnimations = true;
            this.btnManageAuthors.AllowMouseEffects = true;
            this.btnManageAuthors.AllowToggling = false;
            this.btnManageAuthors.AnimationSpeed = 200;
            this.btnManageAuthors.AutoGenerateColors = false;
            this.btnManageAuthors.AutoRoundBorders = false;
            this.btnManageAuthors.AutoSizeLeftIcon = true;
            this.btnManageAuthors.AutoSizeRightIcon = true;
            this.btnManageAuthors.BackColor = System.Drawing.Color.Transparent;
            this.btnManageAuthors.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnManageAuthors.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnManageAuthors.BackgroundImage")));
            this.btnManageAuthors.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageAuthors.ButtonText = "Manage Authors";
            this.btnManageAuthors.ButtonTextMarginLeft = 0;
            this.btnManageAuthors.ColorContrastOnClick = 45;
            this.btnManageAuthors.ColorContrastOnHover = 45;
            this.btnManageAuthors.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnManageAuthors.CustomizableEdges = borderEdges4;
            this.btnManageAuthors.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnManageAuthors.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageAuthors.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageAuthors.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageAuthors.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnManageAuthors.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnManageAuthors.ForeColor = System.Drawing.Color.White;
            this.btnManageAuthors.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageAuthors.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnManageAuthors.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnManageAuthors.IconMarginLeft = 11;
            this.btnManageAuthors.IconPadding = 10;
            this.btnManageAuthors.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnManageAuthors.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnManageAuthors.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnManageAuthors.IconSize = 25;
            this.btnManageAuthors.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnManageAuthors.IdleBorderRadius = 1;
            this.btnManageAuthors.IdleBorderThickness = 1;
            this.btnManageAuthors.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnManageAuthors.IdleIconLeftImage = null;
            this.btnManageAuthors.IdleIconRightImage = null;
            this.btnManageAuthors.IndicateFocus = false;
            this.btnManageAuthors.Location = new System.Drawing.Point(752, 300);
            this.btnManageAuthors.Name = "btnManageAuthors";
            this.btnManageAuthors.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageAuthors.OnDisabledState.BorderRadius = 1;
            this.btnManageAuthors.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageAuthors.OnDisabledState.BorderThickness = 1;
            this.btnManageAuthors.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageAuthors.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageAuthors.OnDisabledState.IconLeftImage = null;
            this.btnManageAuthors.OnDisabledState.IconRightImage = null;
            this.btnManageAuthors.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnManageAuthors.onHoverState.BorderRadius = 1;
            this.btnManageAuthors.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageAuthors.onHoverState.BorderThickness = 1;
            this.btnManageAuthors.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnManageAuthors.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnManageAuthors.onHoverState.IconLeftImage = null;
            this.btnManageAuthors.onHoverState.IconRightImage = null;
            this.btnManageAuthors.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnManageAuthors.OnIdleState.BorderRadius = 1;
            this.btnManageAuthors.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageAuthors.OnIdleState.BorderThickness = 1;
            this.btnManageAuthors.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnManageAuthors.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnManageAuthors.OnIdleState.IconLeftImage = null;
            this.btnManageAuthors.OnIdleState.IconRightImage = null;
            this.btnManageAuthors.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnManageAuthors.OnPressedState.BorderRadius = 1;
            this.btnManageAuthors.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageAuthors.OnPressedState.BorderThickness = 1;
            this.btnManageAuthors.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnManageAuthors.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnManageAuthors.OnPressedState.IconLeftImage = null;
            this.btnManageAuthors.OnPressedState.IconRightImage = null;
            this.btnManageAuthors.Size = new System.Drawing.Size(154, 35);
            this.btnManageAuthors.TabIndex = 6;
            this.btnManageAuthors.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnManageAuthors.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnManageAuthors.TextMarginLeft = 0;
            this.btnManageAuthors.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnManageAuthors.UseDefaultRadiusAndThickness = true;
            this.btnManageAuthors.Click += new System.EventHandler(this.btnManageAuthors_Click);
            // 
            // btnManageBooks
            // 
            this.btnManageBooks.AllowAnimations = true;
            this.btnManageBooks.AllowMouseEffects = true;
            this.btnManageBooks.AllowToggling = false;
            this.btnManageBooks.AnimationSpeed = 200;
            this.btnManageBooks.AutoGenerateColors = false;
            this.btnManageBooks.AutoRoundBorders = false;
            this.btnManageBooks.AutoSizeLeftIcon = true;
            this.btnManageBooks.AutoSizeRightIcon = true;
            this.btnManageBooks.BackColor = System.Drawing.Color.Transparent;
            this.btnManageBooks.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnManageBooks.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnManageBooks.BackgroundImage")));
            this.btnManageBooks.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageBooks.ButtonText = "Manage Books";
            this.btnManageBooks.ButtonTextMarginLeft = 0;
            this.btnManageBooks.ColorContrastOnClick = 45;
            this.btnManageBooks.ColorContrastOnHover = 45;
            this.btnManageBooks.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnManageBooks.CustomizableEdges = borderEdges5;
            this.btnManageBooks.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnManageBooks.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageBooks.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageBooks.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageBooks.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnManageBooks.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnManageBooks.ForeColor = System.Drawing.Color.White;
            this.btnManageBooks.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnManageBooks.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnManageBooks.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnManageBooks.IconMarginLeft = 11;
            this.btnManageBooks.IconPadding = 10;
            this.btnManageBooks.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnManageBooks.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnManageBooks.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnManageBooks.IconSize = 25;
            this.btnManageBooks.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnManageBooks.IdleBorderRadius = 1;
            this.btnManageBooks.IdleBorderThickness = 1;
            this.btnManageBooks.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnManageBooks.IdleIconLeftImage = null;
            this.btnManageBooks.IdleIconRightImage = null;
            this.btnManageBooks.IndicateFocus = false;
            this.btnManageBooks.Location = new System.Drawing.Point(752, 341);
            this.btnManageBooks.Name = "btnManageBooks";
            this.btnManageBooks.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnManageBooks.OnDisabledState.BorderRadius = 1;
            this.btnManageBooks.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageBooks.OnDisabledState.BorderThickness = 1;
            this.btnManageBooks.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnManageBooks.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnManageBooks.OnDisabledState.IconLeftImage = null;
            this.btnManageBooks.OnDisabledState.IconRightImage = null;
            this.btnManageBooks.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnManageBooks.onHoverState.BorderRadius = 1;
            this.btnManageBooks.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageBooks.onHoverState.BorderThickness = 1;
            this.btnManageBooks.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnManageBooks.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnManageBooks.onHoverState.IconLeftImage = null;
            this.btnManageBooks.onHoverState.IconRightImage = null;
            this.btnManageBooks.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnManageBooks.OnIdleState.BorderRadius = 1;
            this.btnManageBooks.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageBooks.OnIdleState.BorderThickness = 1;
            this.btnManageBooks.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnManageBooks.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnManageBooks.OnIdleState.IconLeftImage = null;
            this.btnManageBooks.OnIdleState.IconRightImage = null;
            this.btnManageBooks.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnManageBooks.OnPressedState.BorderRadius = 1;
            this.btnManageBooks.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnManageBooks.OnPressedState.BorderThickness = 1;
            this.btnManageBooks.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnManageBooks.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnManageBooks.OnPressedState.IconLeftImage = null;
            this.btnManageBooks.OnPressedState.IconRightImage = null;
            this.btnManageBooks.Size = new System.Drawing.Size(154, 35);
            this.btnManageBooks.TabIndex = 7;
            this.btnManageBooks.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnManageBooks.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnManageBooks.TextMarginLeft = 0;
            this.btnManageBooks.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnManageBooks.UseDefaultRadiusAndThickness = true;
            // 
            // btnRent
            // 
            this.btnRent.AllowAnimations = true;
            this.btnRent.AllowMouseEffects = true;
            this.btnRent.AllowToggling = false;
            this.btnRent.AnimationSpeed = 200;
            this.btnRent.AutoGenerateColors = false;
            this.btnRent.AutoRoundBorders = false;
            this.btnRent.AutoSizeLeftIcon = true;
            this.btnRent.AutoSizeRightIcon = true;
            this.btnRent.BackColor = System.Drawing.Color.Transparent;
            this.btnRent.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.btnRent.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnRent.BackgroundImage")));
            this.btnRent.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRent.ButtonText = "Rent Books";
            this.btnRent.ButtonTextMarginLeft = 0;
            this.btnRent.ColorContrastOnClick = 45;
            this.btnRent.ColorContrastOnHover = 45;
            this.btnRent.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnRent.CustomizableEdges = borderEdges6;
            this.btnRent.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnRent.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRent.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRent.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRent.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnRent.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.btnRent.ForeColor = System.Drawing.Color.White;
            this.btnRent.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnRent.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnRent.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnRent.IconMarginLeft = 11;
            this.btnRent.IconPadding = 10;
            this.btnRent.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnRent.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnRent.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnRent.IconSize = 25;
            this.btnRent.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.btnRent.IdleBorderRadius = 1;
            this.btnRent.IdleBorderThickness = 1;
            this.btnRent.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.btnRent.IdleIconLeftImage = null;
            this.btnRent.IdleIconRightImage = null;
            this.btnRent.IndicateFocus = false;
            this.btnRent.Location = new System.Drawing.Point(752, 382);
            this.btnRent.Name = "btnRent";
            this.btnRent.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnRent.OnDisabledState.BorderRadius = 1;
            this.btnRent.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRent.OnDisabledState.BorderThickness = 1;
            this.btnRent.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnRent.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnRent.OnDisabledState.IconLeftImage = null;
            this.btnRent.OnDisabledState.IconRightImage = null;
            this.btnRent.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRent.onHoverState.BorderRadius = 1;
            this.btnRent.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRent.onHoverState.BorderThickness = 1;
            this.btnRent.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnRent.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnRent.onHoverState.IconLeftImage = null;
            this.btnRent.onHoverState.IconRightImage = null;
            this.btnRent.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.btnRent.OnIdleState.BorderRadius = 1;
            this.btnRent.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRent.OnIdleState.BorderThickness = 1;
            this.btnRent.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.btnRent.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnRent.OnIdleState.IconLeftImage = null;
            this.btnRent.OnIdleState.IconRightImage = null;
            this.btnRent.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRent.OnPressedState.BorderRadius = 1;
            this.btnRent.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnRent.OnPressedState.BorderThickness = 1;
            this.btnRent.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnRent.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnRent.OnPressedState.IconLeftImage = null;
            this.btnRent.OnPressedState.IconRightImage = null;
            this.btnRent.Size = new System.Drawing.Size(154, 35);
            this.btnRent.TabIndex = 8;
            this.btnRent.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnRent.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnRent.TextMarginLeft = 0;
            this.btnRent.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnRent.UseDefaultRadiusAndThickness = true;
            // 
            // dgv
            // 
            this.dgv.AllowCustomTheming = false;
            this.dgv.AllowUserToAddRows = false;
            this.dgv.AllowUserToDeleteRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dgv.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgv.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgv.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgv.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgv.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgv.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgv.ColumnHeadersHeight = 40;
            this.dgv.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgv.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgv.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgv.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgv.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgv.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgv.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgv.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgv.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgv.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgv.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgv.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgv.CurrentTheme.Name = null;
            this.dgv.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgv.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgv.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgv.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgv.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgv.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgv.EnableHeadersVisualStyles = false;
            this.dgv.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgv.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgv.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgv.HeaderForeColor = System.Drawing.Color.White;
            this.dgv.Location = new System.Drawing.Point(33, 95);
            this.dgv.MultiSelect = false;
            this.dgv.Name = "dgv";
            this.dgv.RowHeadersVisible = false;
            this.dgv.RowTemplate.Height = 40;
            this.dgv.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgv.Size = new System.Drawing.Size(713, 544);
            this.dgv.TabIndex = 9;
            this.dgv.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // Home
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(918, 649);
            this.Controls.Add(this.dgv);
            this.Controls.Add(this.btnRent);
            this.Controls.Add(this.btnManageBooks);
            this.Controls.Add(this.btnManageAuthors);
            this.Controls.Add(this.btnAllAuthors);
            this.Controls.Add(this.btnRentedBooks);
            this.Controls.Add(this.lblMain);
            this.Controls.Add(this.lblDGV);
            this.Controls.Add(this.btnAllBooks);
            this.Name = "Home";
            this.Text = "Home";
            ((System.ComponentModel.ISupportInitialize)(this.dgv)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAllBooks;
        private Bunifu.UI.WinForms.BunifuLabel lblDGV;
        private Bunifu.UI.WinForms.BunifuLabel lblMain;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRentedBooks;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnAllAuthors;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnManageAuthors;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnManageBooks;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnRent;
        private Bunifu.UI.WinForms.BunifuDataGridView dgv;
    }
}